# Generated by Django 5.2.5 on 2025-11-28 01:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPresupuesto',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Ítem')),
                ('descripcion', models.TextField(blank=True, max_length=200, null=True, verbose_name='Descripción del Ítem')),
            ],
            options={
                'verbose_name': 'ítem de presupuesto',
                'verbose_name_plural': 'ítems de presupuesto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de realización o modificación')),
                ('mes', models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], max_length=20, verbose_name='Mes')),
                ('anio', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año')),
                ('descripcion', models.TextField(verbose_name='Descripción general')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'ordering': ['-anio', '-mes'],
                'constraints': [models.UniqueConstraint(fields=('mes', 'anio'), name='unique_mes_anio')],
            },
        ),
        migrations.CreateModel(
            name='DetallePresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_limite', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Límite asignado')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apphela.itempresupuesto', verbose_name='Ítem')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='apphela.presupuesto')),
            ],
        ),
    ]
